schema_version: '2.0'
title: Cao2010 Phage Lambda Lysogeny Lab
description: phage lambda lysogeny switch. References:1. It can be used to explore
  generegulation cao2010 epigenetic state of lysogeny dynamics and compare simulation
  behavior across conditions.
models:
- alias: cao2010_phage_lambda_lysogeny
  path: models/core
  parameters:
    model_path: data/MODEL1308080003.xml
    integration_step: 0.1
- alias: visualisation
  path: models/visualisation
wiring:
- from: cao2010_phage_lambda_lysogeny.ci_repressor
  to:
  - visualisation.cao2010_phage_lambda_lysogeny_ci_repressor
- from: cao2010_phage_lambda_lysogeny.cro_repressor
  to:
  - visualisation.cao2010_phage_lambda_lysogeny_cro_repressor
- from: cao2010_phage_lambda_lysogeny.ci_dimer
  to:
  - visualisation.cao2010_phage_lambda_lysogeny_ci_dimer
- from: cao2010_phage_lambda_lysogeny.cro_dimer
  to:
  - visualisation.cao2010_phage_lambda_lysogeny_cro_dimer
- from: cao2010_phage_lambda_lysogeny.state
  to:
  - visualisation.cao2010_phage_lambda_lysogeny_state
- from: cao2010_phage_lambda_lysogeny.summary
  to:
  - visualisation.cao2010_phage_lambda_lysogeny_summary
- from: cao2010_phage_lambda_lysogeny.species_labels
  to:
  - visualisation.cao2010_phage_lambda_lysogeny_species_labels
io:
  inputs: []
  outputs:
  - name: ci_repressor
    maps_to: cao2010_phage_lambda_lysogeny.ci_repressor
  - name: cro_repressor
    maps_to: cao2010_phage_lambda_lysogeny.cro_repressor
  - name: ci_dimer
    maps_to: cao2010_phage_lambda_lysogeny.ci_dimer
  - name: cro_dimer
    maps_to: cao2010_phage_lambda_lysogeny.cro_dimer
  - name: state
    maps_to: cao2010_phage_lambda_lysogeny.state
  - name: summary
    maps_to: cao2010_phage_lambda_lysogeny.summary
  - name: species_labels
    maps_to: cao2010_phage_lambda_lysogeny.species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
