# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed SBML wrapper for Grunwald2008 - Gene regulation of the Duchenne muscular dystrophy (Petri-net model)."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Grunwald2008GeneRegulationOfTheDuchenneMusModel1403120000Model(TelluriumSBMLBioModule):
    _SBML_ID = 'MODEL1403120000'
    _TITLE = 'Grunwald2008 - Gene regulation of the Duchenne muscular dystrophy (Petri-net model)'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = "species"
    _OBSERVABLES = [
        "P0",
        "P1",
        "P2",
        "P3",
        "P4",
        "P5",
        "P6",
        "P7",
        "P8",
        "P9",
        "P10",
        "P11",
        "P12",
        "P13",
        "P14",
        "P15",
        "P17",
        "P16",
        "P19",
        "P18",
        "P21",
        "P20",
        "P23",
        "P22",
        "P25",
        "P24",
        "P27",
        "P26",
        "P29",
        "P28",
        "P31",
        "P30",
        "P34",
        "P35",
        "P32",
        "P33",
        "P38",
        "P39",
        "P36",
        "P37",
        "P42",
        "P43",
        "P40",
        "P41",
        "P46",
        "P47",
        "P44",
        "P45",
        "P51",
        "P50",
        "P49",
        "P48",
        "P55",
        "P54",
        "P53",
        "P52",
        "P59",
        "P58",
        "P57",
        "P56",
        "P63",
        "P62",
        "P61",
        "P60",
        "P64"
]
    _SPECIES_LABELS = {
        "P0": "PLCe",
        "P1": "compl PIP2 PLCe",
        "P10": "NFATc",
        "P11": "JNK1",
        "P12": "CSNK1A1",
        "P13": "RAC1",
        "P14": "DGC",
        "P15": "Grb2",
        "P16": "PAK1",
        "P17": "NFATc MEF2c GATA4 DNA",
        "P18": "NFATc SP1 SP3 DNA",
        "P19": "NFATc com DNA",
        "P2": "compl Ca channel",
        "P20": "aActin",
        "P21": "ANF",
        "P22": "MLC2",
        "P23": "p21",
        "P24": "UTRNA",
        "P25": "MYF5",
        "P26": "Si RAP2B",
        "P27": "E+RAP2B",
        "P28": "RAP2B",
        "P29": "Dys+",
        "P3": "free Ca ER",
        "P30": "Dys",
        "P31": "Si CSNK1A1",
        "P32": "E+CSNK1A1",
        "P33": "Si MYF5",
        "P34": "Si UTRNA",
        "P35": "Si NFATc",
        "P36": "E+NFATc",
        "P37": "E+calcineurin",
        "P38": "Si Calcineurin",
        "P39": "E+JNK1",
        "P4": "CALR Ca",
        "P40": "Si JNK1",
        "P41": "SOS1",
        "P42": "active DGC",
        "P43": "MEK",
        "P44": "c Jun P",
        "P45": "NFATc nuc",
        "P46": "free NFATc nuc",
        "P47": "active JNK1",
        "P48": "CDK2",
        "P49": "CDK4",
        "P5": "Ca",
        "P50": "CDK6",
        "P51": "E2F active",
        "P52": "RB phos inactive",
        "P53": "E2F phos",
        "P54": "RB",
        "P55": "E2F",
        "P56": "S Phase genes",
        "P57": "E2F RB compl",
        "P58": "act p53",
        "P59": "Calcineurin",
        "P6": "CAM",
        "P60": "NFATc comp DNA",
        "P61": "deact NFATc P",
        "P62": "hypo Silen UTRNA",
        "P63": "hypo Silen MYF5",
        "P64": "p53",
        "P7": "CAM Ca",
        "P8": "act Calcineurin",
        "P9": "NFATc P"
}
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _PARAMETER_INPUTS = {}
    _HEADLINE_OUTPUTS = {'calcium_pool': ('P5', 'native SBML value', 'Ca observable. Maps to SBML symbol `P5`.'), 'nfatc': ('P10', 'native SBML value', 'NFATc observable. Maps to SBML symbol `P10`.'), 'anf_expression': ('P21', 'native SBML value', 'ANF observable. Maps to SBML symbol `P21`.'), 'alpha_actin': ('P20', 'native SBML value', 'aActin observable. Maps to SBML symbol `P20`.')}

    def __init__(self, model_path: str = 'data/MODEL1403120000.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
