schema_version: '2.0'
package: rantasalo2016-induced-stf-b42
version: 1.0.1
title: Rantasalo2016 Induced Stf B42 Lab
description: induced synthetic expression modulator. Rantasalo2015-Synthetic_expresion_modulator_inducedSTF_B42This
  model is part of a family of models describing a modular synthetic expression system
  that modulates the expression level of a gene in S. It can be used to explore generegulation
  rantasalo2016 synthetic expresion modulator indu dynamics and compare simulation
  behavior across conditions.
models:
- alias: rantasalo2016_induced_stf_b42
  path: models/core
  parameters:
    model_path: data/MODEL1510230004.xml
    integration_step: 0.1
- alias: visualisation
  path: models/visualisation
wiring:
- from: rantasalo2016_induced_stf_b42.mcherry_messenger_rna
  to:
  - visualisation.rantasalo2016_induced_stf_b42_mcherry_messenger_rna
- from: rantasalo2016_induced_stf_b42.mcherry_reporter
  to:
  - visualisation.rantasalo2016_induced_stf_b42_mcherry_reporter
- from: rantasalo2016_induced_stf_b42.cytosolic_transcription_factor
  to:
  - visualisation.rantasalo2016_induced_stf_b42_cytosolic_transcription_factor
- from: rantasalo2016_induced_stf_b42.met_transcription_factor
  to:
  - visualisation.rantasalo2016_induced_stf_b42_met_transcription_factor
- from: rantasalo2016_induced_stf_b42.state
  to:
  - visualisation.rantasalo2016_induced_stf_b42_state
- from: rantasalo2016_induced_stf_b42.summary
  to:
  - visualisation.rantasalo2016_induced_stf_b42_summary
- from: rantasalo2016_induced_stf_b42.species_labels
  to:
  - visualisation.rantasalo2016_induced_stf_b42_species_labels
io:
  inputs: []
  outputs:
  - name: mcherry_messenger_rna
    maps_to: rantasalo2016_induced_stf_b42.mcherry_messenger_rna
  - name: mcherry_reporter
    maps_to: rantasalo2016_induced_stf_b42.mcherry_reporter
  - name: cytosolic_transcription_factor
    maps_to: rantasalo2016_induced_stf_b42.cytosolic_transcription_factor
  - name: met_transcription_factor
    maps_to: rantasalo2016_induced_stf_b42.met_transcription_factor
  - name: state
    maps_to: rantasalo2016_induced_stf_b42.state
  - name: summary
    maps_to: rantasalo2016_induced_stf_b42.summary
  - name: species_labels
    maps_to: rantasalo2016_induced_stf_b42.species_labels
runtime:
  duration: 10.0
  communication_step: 1.0
  initial_inputs: {}
